backend:
  name: git-gateway
  # branch: master
# local_backend: true
publish_mode: editorial_workflow
media_folder: src/images
public_folder: /static
i18n:
  structure: multiple_files
  locales: [en, ja]
  default_locale: en
collections:
  - name: "blog"
    i18n: true
    label: "Blog"
    folder: "src/markdown/blog" 
    create: true 
    identifier_field: title
    fields: 
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Location", name: "location", widget: "string", i18n: true}
      - {label: "Category", name: "category", widget: "string", i18n: true}
      - {label: "Date", name: "date", widget: "datetime", i18n: duplicate}
      - {label: "Image", name: "image", widget: "image", i18n: true}
      - {label: "Path", name: "path", widget: "string", hint: "blog/same-as-title", i18n: duplicate}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "ja"], i18n: true}
      - {label: "Description", name: "SEO", widget: "string", i18n: true}
      - {label: "Content", name: "body", widget: "markdown", i18n: true}
  - name: "portfolio"
    i18n: true
    label: "Portfolio"
    folder: "src/markdown/portfolio" 
    create: true 
    identifier_field: title
    fields: 
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Description", name: "description", widget: "string", i18n: true}
      - label: "Images"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        i18n: true
        field: {label: Image, name: image, widget: image,  i18n: true}
      - {label: "Link", name: "link", widget: "string", i18n: true}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "ja"], i18n: true}
      - {label: "Date", name: "date", widget: "datetime", i18n: duplicate}
      - {label: "Content", name: "body", widget: "markdown", i18n: true}