backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: src/images
public_folder: /static
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files
  locales: [en, ja]
  default_locale: en
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/markdown/blog" 
    create: true 
    identifier_field: title
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Path", name: "path", widget: "string", hint: "blog/same-as-title"}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "ja"]}
      - {label: "Description", name: "SEO", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/markdown/portfolio" 
    create: true 
    identifier_field: title
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Locale", name: "locale", widget: "select", options: ["en", "ja"]}
      - {label: "Date", name: "date", widget: "datetime"}